version: '3.8'

services:
  jenkins:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.jenkins
    image: vsiraparapu/jenkins:latest
    container_name: jenkins
    restart: always
    pull_policy: always
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-cd-network

volumes:
  jenkins_home:

networks:
  ci-cd-network:
    external: true